#!/bin/bash
# Using bash just for associative arrays

DRYRUN=0
FORCEY=0
UNPROCPKGS=""
PROCESSEDPKGS=""

usage() {
    echo "Usage: install|remove [-y | --dry-run] command1 ..."
    echo "Usage: up|dup # update / system (including kernel) update"
    echo "Usage: --list-pkgs"
    echo "Usage: --list-supported"
}

empty() {
    return
}

debian_up() {
    apt-get update && apt-get upgrade && apt-get autoremove && apt-get clean
}

debian_dup() {
    apt-get update && apt-get dist-upgrade && apt-get autoremove && apt-get clean
}

fedora_dup() {
    dnf update
}

centos_dup() {
    yum update
}

pacman_dup() {
    pacman -Syu
}

# $1 - environment name
up() {
    if [ $1 = debian ]; then
        debian_up
        exit 0
    elif [ $1 = fedora ]; then
        fedora_dup # this is not typo, fedora_up === fedora_dup
        exit 0
    elif [ $1 = centos ]; then
        centos_dup # this is not typo, centos_up === centos_dup
        exit 0
    elif [ $1 = pacman ]; then
        pacman_dup # this is not typo, pacman_up === pacman_dup
        exit 0
    else
        echo "NYI"
        exit 1
    fi
}

# $1 - environment name
dup() {
    if [ $1 = debian ]; then
        debian_dup
        exit 0
    elif [ $1 = fedora ]; then
        fedora_dup
        exit 0
    elif [ $1 = centos ]; then
        centos_dup
        exit 0
    elif [ $1 = pacman ]; then
        pacman_dup
        exit 0
    else
        echo "NYI"
        exit 1
    fi
}

detect_env() {
    grep -q "[Dd]ebian" /etc/os-release 2> /dev/null
    if [ $? = 0 ]; then echo debian; return; fi

    grep -q "os/illumos/dyson/apt" /etc/apt/sources.list 2> /dev/null
    if [ $? = 0 ]; then echo debian; return; fi

    grep -q "ID=\"centos\"" /etc/os-release 2> /dev/null
    if [ $? = 0 ]; then echo centos; return; fi

    grep -q "[Ff]edora" /etc/os-release 2> /dev/null
    if [ $? = 0 ]; then echo fedora; return; fi

    grep -q "manjaro" /etc/os-release 2> /dev/null
    if [ $? = 0 ]; then echo pacman; return; fi

    echo ""
}

list_supported() {
    echo "Debian (at least 8)"
    echo "Ubuntu (at least 16.04)"
    echo "Fedora (at least 24)"
    echo "CentOS (at least 7)"
    echo "Dyson (at least Dufay)"
    echo "Manjaro (at least 17.0)"
}

en=$(detect_env)
if [ x$en = x ]; then
    echo "Unsupported OS/Environment. Patch me and merge request or contact support"
    exit 1
fi

declare -A map
# touples command=package should not be listed
if [ $en = debian ]; then
    map[7z]=p7zip-full
    map[7za]=p7zip-full
    #map[7zr]=p7zip # for command with absence packages for all environments will be no support
    map[qmake-qt4]=qt4-make
elif [ $en = redhat ] || [ $en = fedora ] || [ $en = centos ]; then
    map[sshfs]=fuse-sshfs
    map[qtcreator]=qt-creator
    map[7z]=p7zip-plugins
    map[7za]=p7zip
    #map[7zr]=n/a
    map[g++]=gcc-c++
    map[qmake-qt4]=qt-devel
    map[gnat]=gcc-gnat
    map[wireshark]=wireshark-gtk
elif [ $en = pacman ]; then
    map[7z]=p7zip
    map[7za]=p7zip
    map[g++]=gcc
    map[qmake-qt4]=qt4
    map[gnat]=gcc-ada
    map[wireshark]=wireshark-gtk
else
    echo NYI
    exit 1
fi;

if [ $# = 1 ]; then
    if [ $1 = --list-pkgs ]; then for i in "${!map[@]}"; do echo $i; done; exit 0; fi
    if [ $1 = --list-supported ]; then list_supported; exit 0; fi
    if [ $1 = up ]; then up $en; fi
    if [ $1 = dup ]; then dup $en; fi
fi

if [ $# -ge 1 ]; then
    if [ $1 != install ] && [ $1 != remove ]; then
        usage;
        exit 0;
    fi
else
    usage;
    exit 0;
fi

if [ $en = debian ]; then
    cmd=apt-get $1
elif [ $en = fedora ]; then
    cmd=dnf $1
elif [ $en = centos ]; then
    cmd=yum $1
elif [ $en = pacman ]; then
    if [ $1 = install ]; then
        cmd="pacman -S"
    elif [ $1 = remove ]; then
        cmd="pacman -Rs"
    else
        echo "Internal error"
        exit 1
    fi
else
    echo "Internal error: add check for a new environment"
    exit 1
fi

for i in $@; do
    if [ $i = "-y" ]; then FORCEY=1;
    elif [ $i = "--dry-run" ]; then DRYRUN=1;
    elif [ $i = $1 ]; then empty; # just do nothing, needed to skip first argument
    else
        UNPROCPKGS="$i $UNPROCPKGS"
    fi
done

for i in $UNPROCPKGS; do
    if ! [ ${map[$i]+_} ]; then
        # there is no such key in map, using directly
        # (in hope command=package for all environments)
        PROCESSEDPKGS="$i $PROCESSEDPKGS"
    else
        # substitute command $i using map
        PROCESSEDPKGS="${map[$i]} $PROCESSEDPKGS"
    fi
done

finalCmd="$cmd $PROCESSEDPKGS"
if [ $FORCEY = 1 ]; then
    if [ $en != pacman ]; then
        finalCmd="$finalCmd -y"
    else
        echo "NOTE: pacman doesn't support -y key (yet), ignoring -y"
    fi
fi

if [ $DRYRUN = 1 ]; then
    echo "$finalCmd"
    exit 0;
fi

$finalCmd
